[server]
node = "gw-01"
tcp_bind = "localhost:1001"
rpc_bind = "localhost:2001"

[http]
bind = "localhost:8080"

[redis]
address = "116.196.102.109:6379"
password = "zhangqing0912"

[zookeeper]
address = "116.196.102.109"

[influxdb]
address = "http://120.77.77.254:8086"
username = "root"
password = "root"
database = "zpush"